- hosts: praktikum
  become: yes
  vars:
    project_directory: /opt/wordpress
  tasks:
    - name: Установить необходимые пакеты
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Добавить официальные GPG ключи Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить репозиторий Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Установить Docker
      apt:
        name: 
          - docker-ce
          - docker-compose
        state: latest

    - name: Убедиться, что Docker запущен
      service:
        name: docker
        state: started
        enabled: yes

    - name: Make directory for WordPress
      file:
        path: "{{ project_directory }}"
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: "{{ project_directory }}/docker-compose.yml"

    - name: Runs Wordpress from Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ project_directory }}"

    - name: Проверка статуса контейнеров
      command: docker-compose ps
      args:
        chdir: "{{ project_directory }}"
      register: compose_status

    - name: Вывод статуса контейнеров
      debug:
        var: compose_status.stdout_lines
