version: '3.8'
services:
  db:
    image: mysql:lts
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wp_db
        MYSQL_USER: mysql_user
        MYSQL_PASSWORD: mysql_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: mysql_user
        WORDPRESS_DB_PASSWORD: mysql_password
        WORDPRESS_DB_NAME: wp_db
    depends_on:
      - db

volumes:
  db_data:
