version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
        WORDPRESS_DB_HOST: master:3306
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: rootpass
        WORDPRESS_DB_NAME: replication_db
    depends_on:
      - master
      - replica

  master:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: replication_db
    ports:
      - "3307:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - master_data:/var/lib/mysql

  replica:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: replication_db
    ports:
      - "3308:3306"
    depends_on:
      - master
    volumes:
      - ./replica/my.cnf:/etc/mysql/my.cnf
      - ./replica/init.sql:/docker-entrypoint-initdb.d/init.sql
      - replica_data:/var/lib/mysql

volumes:
  master_data:
  replica_data:
